[template]
    extension = ".tmpl"

[git]
    autoCommit = true
    autoPush = true

[data]
    openai_api_key = "{{ (secret \"keyring:chezmoi/openai_api_key\") }}"
    supabase_access_token = "{{ (secret \"keyring:chezmoi/supabase_access_token\") }}"